export const SET_IS_LOADING = "SET_IS_LOADING"

// auth
export const SET_USER = "SET_USER"
export const UPDATE_USER = "UPDATE_USER"

// get list of users
export const SET_ALL_USERS = "SET_ALL_USERS"
export const TOGGLE_DYSLEXIA_FONT = "TOGGLE_DYSLEXIA_FONT"

// classrooms
export const LOAD_CLASSROOMS = "LOAD_CLASSROOMS"
export const ADD_CLASSROOM = "ADD_CLASSROOM"
export const ADD_REQUEST = "ADD_REQUEST"
export const WITHDRAW_REQUEST = "WITH_DRAW_REQUEST"

// classroom
export const LOAD_CLASSROOM = "LOAD_CLASSROOM"
export const LOAD_CLASSROOM_REQUESTS = "LOAD_CLASSROOM_REQUESTS"
export const SET_CONTENT_MODERATION = "SET_CONTENT_MODERATION"
export const ADD_CHANNEL_TO_CLASSROOM = "ADD_CHANNEL_TO_CLASSROOM"
export const REMOVE_CHANNEL_FROM_CLASSROOM = "REMOVE_CHANNEL_FROM_CLASSROOM"
export const UPDATE_CHANNEL_OF_CLASSROOM = "UPDATE_CHANNEL_OF_CLASSROOM"
export const ADD_MEMBER_TO_CLASSROOM = "ADD_MEMBER_TO_CLASSROOM"
export const REMOVE_MEMBER_FROM_CLASSROOM = "REMOVE_MEMBER_FROM_CLASSROOM"
export const DELETE_CLASSROOM = "DELETE_CLASSROOM"

// chat
export const LOAD_CHAT = "LOAD_CHAT"
export const SET_CHANNEL = "SET_CHANNEL"
export const SET_RECEIVER = "SET_RECEIVER"
export const ADD_MESSAGE_TO_CHAT = "ADD_MESSAGE_TO_CHAT"
export const ADD_REACTION_TO_MESSAGE = "ADD_REACTION_TO_MESSAGE"
export const REMOVE_REACTION_TO_MESSAGE = "REMOVE_REACTION_TO_MESSAGE"
export const EDIT_MESSAGE = "EDIT_MESSAGE"
export const DELETE_MESSAGE = "DELETE_MESSAGE"

// notes
export const LOAD_NOTES = "LOAD_NOTES"
export const LOAD_NOTE = "LOAD_NOTE"
export const ADD_NOTE = "ADD_NOTE"
export const EDIT_NOTE = "EDIT_NOTE"
export const REMOVE_NOTE = "REMOVE_NOTE"