export const SET_IS_LOADING = "SET_IS_LOADING"

// auth
export const SET_USER = "SET_USER"

// get list of users
export const SET_ALL_USERS = "SET_ALL_USERS"

// classrooms
export const LOAD_CLASSROOMS = "LOAD_CLASSROOMS"
export const ADD_CLASSROOM = "ADD_CLASSROOM"
export const LEAVE_CLASSROOM = "LEAVE_CLASSROOM"
export const ADD_REQUEST = "ADD_REQUEST"
export const WITHDRAW_REQUEST = "WITH_DRAW_REQUEST"

// classroom
export const LOAD_CLASSROOM = "LOAD_CLASSROOM"
export const LOAD_CLASSROOM_REQUESTS = "LOAD_CLASSROOM_REQUESTS"

// chat
export const LOAD_CHAT = "LOAD_CHAT"
export const SET_CHANNEL = "SET_CHANNEL"
export const SET_RECEIVER = "SET_RECEIVER"
export const ADD_MESSAGE_TO_CHAT = "ADD_MESSAGE_TO_CHAT"
export const ADD_REACTION_TO_MESSAGE = "ADD_REACTION_TO_MESSAGE"
export const REMOVE_REACTION_TO_MESSAGE = "REMOVE_REACTION_TO_MESSAGE"
export const EDIT_MESSAGE = "EDIT_MESSAGE"
export const DELETE_MESSAGE = "DELETE_MESSAGE"