export const SET_IS_LOADING = "SET_IS_LOADING"

// auth
export const SET_USER = "SET_USER"

// get list of users
export const SET_ALL_USERS = "SET_ALL_USERS"

// classrooms
export const LOAD_CLASSROOMS = "LOAD_CLASSROOMS"
export const ADD_CLASSROOM = "ADD_CLASSROOM"
export const LEAVE_CLASSROOM = "LEAVE_CLASSROOM"
export const ADD_REQUEST = "ADD_REQUEST"
export const WITHDRAW_REQUEST = "WITH_DRAW_REQUEST"

// classroom
export const LOAD_CLASSROOM = "LOAD_CLASSROOM"
export const LOAD_CLASSROOM_REQUESTS = "LOAD_CLASSROOM_REQUESTS"
export const SET_CONTENT_MODERATION = "SET_CONTENT_MODERATION"

// chat
export const LOAD_CHAT = "LOAD_CHAT"
export const SET_CHANNEL = "SET_CHANNEL"
export const SET_RECEIVER = "SET_RECEIVER"
export const ADD_MESSAGE_TO_CHAT = "ADD_MESSAGE_TO_CHAT"
export const ADD_REACTION_TO_MESSAGE = "ADD_REACTION_TO_MESSAGE"
export const REMOVE_REACTION_TO_MESSAGE = "REMOVE_REACTION_TO_MESSAGE"
export const EDIT_MESSAGE = "EDIT_MESSAGE"
export const DELETE_MESSAGE = "DELETE_MESSAGE"

// socket chat events
export const CHANNEL_NEW_CHAT_MESSAGE_EVENT = "CHANNEL_NEW_CHAT_MESSAGE_EVENT";
export const CHANNEL_EDIT_MESSAGE_EVENT = "CHANNEL_EDIT_MESSAGE_EVENT";
export const CHANNEL_DELETE_MESSAGE_EVENT = "CHANNEL_DELETE_MESSAGE_EVENT";
export const CHANNEL_MESSAGE_NEW_REACTION_EVENT = "CHANNEL_MESSAGE_NEW_REACTION_EVENT";
export const CHANNEL_MESSAGE_DELETE_REACTION_EVENT = "CHANNEL_MESSAGE_DELETE_REACTION_EVENT";
export const NEW_CHAT_MESSAGE_EVENT = "NEW_CHAT_MESSAGE_EVENT";
export const EDIT_MESSAGE_EVENT = "EDIT_MESSAGE_EVENT";
export const DELETE_MESSAGE_EVENT = "DELETE_MESSAGE_EVENT";
export const MESSAGE_NEW_REACTION_EVENT = "MESSAGE_NEW_REACTION_EVENT";
export const MESSAGE_DELETE_REACTION_EVENT = "MESSAGE_DELETE_REACTION_EVENT";

export const LOAD_NOTES = "LOAD_NOTES"
export const LOAD_NOTE = "LOAD_NOTE"
export const ADD_NOTE = "ADD_NOTE"
export const EDIT_NOTE = "EDIT_NOTE"
export const REMOVE_NOTE = "REMOVE_NOTE"
export const TOGGLE_DYSLEXIA_FONT = "TOGGLE_DYSLEXIA_FONT"