// socket events
// channel messages
export const CHANNEL_NEW_CHAT_MESSAGE_EVENT = "CHANNEL_NEW_CHAT_MESSAGE_EVENT";
export const CHANNEL_EDIT_MESSAGE_EVENT = "CHANNEL_EDIT_MESSAGE_EVENT";
export const CHANNEL_DELETE_MESSAGE_EVENT = "CHANNEL_DELETE_MESSAGE_EVENT";
export const CHANNEL_MESSAGE_NEW_REACTION_EVENT = "CHANNEL_MESSAGE_NEW_REACTION_EVENT";
export const CHANNEL_MESSAGE_DELETE_REACTION_EVENT = "CHANNEL_MESSAGE_DELETE_REACTION_EVENT";
// direct messages
export const NEW_CHAT_MESSAGE_EVENT = "NEW_CHAT_MESSAGE_EVENT";
export const EDIT_MESSAGE_EVENT = "EDIT_MESSAGE_EVENT";
export const DELETE_MESSAGE_EVENT = "DELETE_MESSAGE_EVENT";
export const MESSAGE_NEW_REACTION_EVENT = "MESSAGE_NEW_REACTION_EVENT";
export const MESSAGE_DELETE_REACTION_EVENT = "MESSAGE_DELETE_REACTION_EVENT";
// classroom related
export const NEW_CHANNEL = "NEW_CHANNEL";
export const UPDATE_CHANNEL = "UPDATE_CHANNEL";
export const REMOVE_CHANNEL = "REMOVE_CHANNEL"
export const CONTENT_MODERATION_UPDATE = "CONTENT_MODERATION_UPDATE"
export const NEW_MEMBER = "NEW_MEMBER";
export const DELETE_CLASSROOM = "DELETE_CLASSROOM";
export const REMOVE_MEMBER = "REMOVE_MEMBER";